"""add node country

Revision ID: 3fa7d891b666
Revises: 449751137a69
Create Date: 2026-08-20 17:52:15.697906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fa7d891b666'
down_revision = '449751137a69'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('country', sa.String(length=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'country')
    # ### end Alembic commands ###
