"""add inbound reality private key

Revision ID: f05edd038082
Revises: 3fa7d891b666
Create Date: 2026-08-20 18:07:13.687252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f05edd038082'
down_revision = '3fa7d891b666'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inbounds', sa.Column('reality_private_key_encrypted', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inbounds', 'reality_private_key_encrypted')
    # ### end Alembic commands ###
